force-app/main/default/objects/sObjectTriggerAction__mdt/sObjectTriggerAction__mdt.object-meta.xml
<CustomObject>
    <label>sObject Trigger Action</label>
    <pluralLabel>sObject Trigger Actions</pluralLabel>
</CustomObject>

force-app/main/default/objects/sObjectTriggerAction__mdt/fields/BypassHandler__c.field-meta.xml
<CustomField>
    <fullName>BypassHandler__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Enable/Disable Bypass for the activities like migration</inlineHelpText>
    <label>Bypass Handler</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sObjectTriggerAction__mdt/fields/BypassUser__c.field-meta.xml
<CustomField>
    <fullName>BypassUser__c</fullName>
    <label>Bypass User</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/sObjectTriggerAction__mdt/fields/ExecutionOrder__c.field-meta.xml
<CustomField>
    <fullName>ExecutionOrder__c</fullName>
    <inlineHelpText>The order in which the Trigger Handler should execute</inlineHelpText>
    <label>Execution Order</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sObjectTriggerAction__mdt/fields/HandlerClassName__c.field-meta.xml
<CustomField>
    <fullName>HandlerClassName__c</fullName>
    <inlineHelpText>The name of the Handler class which is using this framework</inlineHelpText>
    <label>Handler Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sObjectTriggerAction__mdt/fields/Is_After_Delete__c.field-meta.xml
<CustomField>
    <fullName>Is_After_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is After Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sObjectTriggerAction__mdt/fields/Is_After_Insert__c.field-meta.xml
<CustomField>
    <fullName>Is_After_Insert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is After Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sObjectTriggerAction__mdt/fields/Is_After_Undelete__c.field-meta.xml
<CustomField>
    <fullName>Is_After_Undelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is After Undelete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sObjectTriggerAction__mdt/fields/Is_After_Update__c.field-meta.xml
<CustomField>
    <fullName>Is_After_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is After Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sObjectTriggerAction__mdt/fields/Is_Before_Delete__c.field-meta.xml
<CustomField>
    <fullName>Is_Before_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Before Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sObjectTriggerAction__mdt/fields/Is_Before_Insert__c.field-meta.xml
<CustomField>
    <fullName>Is_Before_Insert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Before Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sObjectTriggerAction__mdt/fields/Is_Before_Update__c.field-meta.xml
<CustomField>
    <fullName>Is_Before_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Before Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sObjectTriggerAction__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Enable/Disable the Handler Class</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sObjectTriggerAction__mdt/fields/sObject_Trigger_Setting__c.field-meta.xml
<CustomField>
    <fullName>sObject_Trigger_Setting__c</fullName>
    <inlineHelpText>Object Name for which the trigger handler is</inlineHelpText>
    <label>sObject Trigger Setting</label>
    <referenceTo>sObjectTriggerSetting__mdt</referenceTo>
    <relationshipLabel>sObject Trigger Actions</relationshipLabel>
    <relationshipName>sObject_Trigger_Actions</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/sObjectTriggerSetting__mdt/fields/Bypass__c.field-meta.xml
<CustomField>
    <fullName>Bypass__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Enable/Disable Bypass for the activities like migration</inlineHelpText>
    <label>Bypass</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sObjectTriggerSetting__mdt/fields/BypassUsers__c.field-meta.xml
<CustomField>
    <fullName>BypassUsers__c</fullName>
    <inlineHelpText>Provide the Usernames comma separated for whom the trigger should not execute!</inlineHelpText>
    <label>Bypass Users</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/sObjectTriggerSetting__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable/disable trigger for this object</description>
    <inlineHelpText>Enable/disable trigger for this object</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sObjectTriggerSetting__mdt/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <description>SObject API name (e.g., &apos;Account&apos;, &apos;Contact&apos;, &apos;Payment__c&apos;)</description>
    <inlineHelpText>SObject API name (e.g., &apos;Account&apos;, &apos;Contact&apos;, &apos;Payment__c&apos;)</inlineHelpText>
    <label>Object API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TriggerManager.cls
public class TriggerManager {

    public static void run(String objectApiName){
        List<sObjectTriggerAction__mdt> triggerAcctionRecords = getConfigs(objectApiName);
        for(Integer i=0; i< triggerAcctionRecords.size(); i++){
            sObjectTriggerAction__mdt action = triggerAcctionRecords.get(i);
            /** Check for which event the trigger is valid **/
            // Trigger.OperationType - BEFORE_INSERT ~= Is_Before_Insert__c
            // 'Is_'+Trigger.OperationType+'__c' != Is_BEFORE_INSERT__c
            String fieldApiName = 'Is_'+Trigger.OperationType+'__c';
            String bypassUserNames = action.BypassUser__c ?? '' + ','+action.sObject_Trigger_Setting__r.BypassUsers__c ?? '';
            //System.debug(' By Pass User Names '+ bypassUserNames);
            if((Boolean)action.get(fieldApiName) && byPassUser(bypassUserNames) == false ){ // sObject
                TriggerHandler handler = (TriggerHandler)Type.forName(action.HandlerClassName__c).newInstance();
                List<sObject> records = handler.filterRecords();
                if(records?.size()>0){
                    handler.execute(records);
                }
            }
        }
    }
    
    private static Boolean byPassUser(String userNames){
        Boolean isByPass = userNames?.contains(UserInfo.getUserName());
        //System.debug(' By Pass User '+ isByPass);
        return isByPass;
    }
    
    public static List<sObjectTriggerAction__mdt> getConfigs(String objectApiName){
        List<sObjectTriggerAction__mdt> triggerAcctionRecords = [SELECT  HandlerClassName__c, BypassUser__c, 
                                            Is_Before_Insert__c, Is_After_Insert__c, Is_After_Update__c, 
                                            Is_Before_Update__c, Is_After_Undelete__c, Is_After_Delete__c, 
                                            Is_Before_Delete__c, ExecutionOrder__c, sObject_Trigger_Setting__r.BypassUsers__c
                                        FROM 
                                           sObjectTriggerAction__mdt
                                        WHERE 
                                            sObject_Trigger_Setting__r.Object_API_Name__c =: objectApiName AND
                                        	IsActive__c = True AND 
                                            BypassHandler__c = False AND
                                        	sObject_Trigger_Setting__r.Is_Active__c = True AND 
                                        	sObject_Trigger_Setting__r.Bypass__c = False
                                        ORDER BY 
                                            ExecutionOrder__c ASC NULLS LAST
                                    ];
        return triggerAcctionRecords;
    }
}