force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CourseHandlerTest.cls
@IsTest(seeAllData=false)
public class CourseHandlerTest {
    
    @TestSetup
    private static void setupMethod(){
        
        /* Profile standardProfile = [SELECT Id FROM Profile WHERE Name = 'Property Management Admin' LIMIT 1];
        User testUser = new User(
            FirstName = 'John Smith',
            LastName = 'Doe',
            Email = 'testuser@example.com',
            Username = 'testuser@example.com.test.testing',
            Alias = 'tuser',
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            ProfileId = standardProfile.Id
        );
        insert testUser; */
        User testUser = TestDataFactory.createUser('Property Management Admin', 'Admin', 'User', true);
        System.runAs(testUser){
            /* Course__c course = new Course__c(
                Name = 'Salesforce DevOps',
                StartDate__c = System.today(),
                EndDate__c = System.today().addDays(83),
                Price__c = 4343
            );
            insert course; */
            Course__c course = TestDataFactory.createCourse('Salesforce Test Data Factory', 8234, false);
            course.EndDate__c = System.today().addDays(12);
            insert course;
            
            Account acc = TestDataFactory.createAccount('Salesforce.com', 'Technology', false);
            acc.Description = '';
            acc.Active__c = 'Yes';
            acc.AccountSource = 'Web';
            acc.AccountNumber = '';
            acc.Phone = '';
            insert acc;
        }
    }

    @IsTest(seeAllData=false)
    private static void createCourseTest(){
        Test.startTest();
        new CourseHandler().createCourse();
        Test.stopTest();
    }
    @IsTest
    private static void listCourseQueryWithBindsTest(){
        User testUser = [SELECT Id, Name FROM User WHERE UserName = 'testuser@example.com.test.testing' LIMIT 1];
        Test.startTest();
        System.runAs(testUser){
            List<Course__c> courseList = new CourseHandler().listCourseQueryWithBinds(1000.00);
            System.debug('courseList In Test Class \n '+ courseList);
        }
        Test.stopTest();
    }
    
    @IsTest
    private static void listCourseQueryWithBindsTest1(){
        User testUser = [SELECT Id, Name FROM User WHERE UserName = 'testuser@example.com.test.testing' LIMIT 1];
        Test.startTest();
        System.runAs(testUser){
            List<Course__c> courseList = new CourseHandler().listCourseQueryWithBinds(1000.00);
            System.debug('courseList In Test Class \n '+ courseList);
        }
        Test.stopTest();
    }
    @IsTest
    private static void listCoursesWithUserModeTest(){
        Test.startTest();
        List<Course__c> courseList = new CourseHandler().listCoursesWithUserMode();
        Test.stopTest();
        System.debug('courseList In Test Class \n '+ courseList);
    }
}