force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/CourseDuration__c.field-meta.xml
<CustomField>
    <fullName>CourseDuration__c</fullName>
    <label>Course Duration</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CourseTriggerHandler.cls
public with sharing class CourseTriggerHandler extends TriggerHandler {

    public override List<SObject> filterRecords(){
        List<SObject> recordsToProcess = new List<SObject>();
        for(Course__c course: (List<Course__c>)newRecords){
            if(course.StartDate__c <> null ){
                recordsToProcess.add(course);
            }
        }
        System.debug('Inside the filterRecords Method - '+recordsToProcess?.size());
        return recordsToProcess;
    }
    public override void execute(List<SObject> records){ /// filtered records
        /** Business Logic **/
        System.debug('Inside the Execute Method - '+records?.size());
        for(Course__c course: (List<Course__c>)records){
            //course.Price__c = 8978;
            if(course.EndDate__c <> null){
                course.CourseDuration__c = course.StartDate__c.daysBetween(course.EndDate__c);
            }
        }
        /*
        CourseHandler handler = new CourseHandler();
        handler.listCourse();
        */
        // new CourseHandler().listCoursesWithSecurity();
        // new CourseHandler().listCoursesWithUserMode();
        // new CourseHandler().listCoursesWithDatabaseQuery();
        
        new CourseHandler().listCourseQueryWithBinds(1000);
    }
}